/**
 * 18 个 mock 业务功能点 —— Phase 2G V0 演示数据。
 *
 * 5 业务域分布（spec §3）：
 *   - 订单管理: 4  (order_create, order_refund, order_query, order_close)
 *   - 用户管理: 4  (user_register, user_login, user_profile, user_oauth_bind)
 *   - 财务管理: 3  (finance_reconcile, finance_payout, finance_refund_audit)
 *   - 库存管理: 4  (inventory_stock_in, inventory_stock_out, inventory_lock, inventory_alert)
 *   - 报表分析: 3  (report_daily_sales, report_user_growth, report_risk_dashboard)
 *
 * 路径前缀统一：C:/demo/order-service/src/main/java/com/xxx/...
 * 严禁 DSN 形态字符串（CLAUDE.md §5）。
 */
import type { Feature } from '@/types/biznav';

const PROJECT_ROOT = 'C:/demo/order-service';
const PROJECT_NAME = 'demo';
const NOW = Date.now();

export const MOCK_FEATURES: Feature[] = [
  // ========== 订单管理 ==========
  {
    id: 'order_create',
    name: '订单创建',
    description: '用户提交购物车商品，生成订单并扣减库存',
    category: '订单管理',
    project_name: PROJECT_NAME,
    project_root: PROJECT_ROOT,
    related_files: [
      { path: 'src/main/java/com/xxx/controller/OrderController.java', role: 'API 入口' },
      { path: 'src/main/java/com/xxx/service/OrderService.java', role: '业务逻辑' },
      { path: 'src/main/resources/mapper/OrderMapper.xml', role: '数据库操作' },
    ],
    related_apis: [{ method: 'POST', path: '/api/v1/orders', description: '创建订单接口' }],
    related_tables: [
      { name: 't_order', description: '订单主表' },
      { name: 't_order_item', description: '订单明细表' },
    ],
    business_rules: ['库存不足时返回错误码 1001', '订单金额超过 10000 需要人工审核'],
    risk_level: 'high',
    source: 'manual',
    ai_confidence: null,
    version: 1,
    created_at: NOW - 30 * 86400_000,
    updated_at: NOW - 7 * 86400_000,
  },
  {
    id: 'order_refund',
    name: '订单退款',
    description: '已支付订单全额 / 部分退款，原路退回',
    category: '订单管理',
    project_name: PROJECT_NAME,
    project_root: PROJECT_ROOT,
    related_files: [
      { path: 'src/main/java/com/xxx/service/RefundService.java', role: '业务逻辑' },
      { path: 'src/main/java/com/xxx/integration/PaymentGateway.java', role: '外部依赖' },
    ],
    related_apis: [{ method: 'POST', path: '/api/v1/orders/{id}/refund', description: '申请退款' }],
    related_tables: [
      { name: 't_refund', description: '退款记录表' },
      { name: 't_order', description: '订单主表' },
    ],
    business_rules: ['已发货订单退款需客服审批', '原支付渠道 3-5 工作日到账'],
    risk_level: 'high',
    source: 'manual',
    ai_confidence: null,
    version: 1,
    created_at: NOW - 28 * 86400_000,
    updated_at: NOW - 5 * 86400_000,
  },
  {
    id: 'order_query',
    name: '订单查询',
    description: '多维度查询订单列表 + 详情',
    category: '订单管理',
    project_name: PROJECT_NAME,
    project_root: PROJECT_ROOT,
    related_files: [
      { path: 'src/main/java/com/xxx/controller/OrderQueryController.java', role: 'API 入口' },
    ],
    related_apis: [
      { method: 'GET', path: '/api/v1/orders', description: '订单列表（分页）' },
      { method: 'GET', path: '/api/v1/orders/{id}', description: '订单详情' },
    ],
    related_tables: [{ name: 't_order', description: '订单主表（只读）' }],
    business_rules: ['普通员工只能看自己负责的订单'],
    risk_level: 'low',
    source: 'manual',
    ai_confidence: null,
    version: 1,
    created_at: NOW - 25 * 86400_000,
    updated_at: NOW - 10 * 86400_000,
  },
  {
    id: 'order_close',
    name: '订单关闭',
    description: '超时未支付或取消订单自动关闭',
    category: '订单管理',
    project_name: PROJECT_NAME,
    project_root: PROJECT_ROOT,
    related_files: [
      { path: 'src/main/java/com/xxx/scheduler/OrderCloseJob.java', role: '定时任务' },
    ],
    related_apis: [],
    related_tables: [{ name: 't_order', description: '订单主表' }],
    business_rules: ['未支付订单 30 分钟自动关闭', '已发货订单不可关闭只能退款'],
    risk_level: 'medium',
    source: 'manual',
    ai_confidence: null,
    version: 1,
    created_at: NOW - 20 * 86400_000,
    updated_at: NOW - 3 * 86400_000,
  },
  // ========== 用户管理 ==========
  {
    id: 'user_register',
    name: '用户注册',
    description: '手机号 / 邮箱注册，验证码 + 实名认证',
    category: '用户管理',
    project_name: PROJECT_NAME,
    project_root: PROJECT_ROOT,
    related_files: [
      { path: 'src/main/java/com/xxx/controller/UserController.java', role: 'API 入口' },
      { path: 'src/main/java/com/xxx/service/UserService.java', role: '业务逻辑' },
    ],
    related_apis: [
      { method: 'POST', path: '/api/v1/users/register', description: '注册新用户' },
      { method: 'POST', path: '/api/v1/users/verify-sms', description: '发送短信验证码' },
    ],
    related_tables: [
      { name: 't_user', description: '用户主表' },
      { name: 't_user_verification', description: '实名认证记录' },
    ],
    business_rules: ['同一手机号 1 小时内最多发 5 条验证码', '实名认证需对接公安部接口'],
    risk_level: 'medium',
    source: 'manual',
    ai_confidence: null,
    version: 1,
    created_at: NOW - 35 * 86400_000,
    updated_at: NOW - 12 * 86400_000,
  },
  {
    id: 'user_login',
    name: '用户登录',
    description: '账号密码 / 短信验证码 / 微信 OAuth 三种登录方式',
    category: '用户管理',
    project_name: PROJECT_NAME,
    project_root: PROJECT_ROOT,
    related_files: [
      { path: 'src/main/java/com/xxx/controller/AuthController.java', role: 'API 入口' },
      { path: 'src/main/java/com/xxx/security/JwtProvider.java', role: 'JWT 签发' },
    ],
    related_apis: [
      { method: 'POST', path: '/api/v1/auth/login', description: '账号密码登录' },
      { method: 'POST', path: '/api/v1/auth/login-sms', description: '短信验证码登录' },
    ],
    related_tables: [
      { name: 't_user', description: '用户主表' },
      { name: 't_login_log', description: '登录日志（风控）' },
    ],
    business_rules: ['连续 5 次密码错误锁定 30 分钟', '异地登录触发风控验证'],
    risk_level: 'medium',
    source: 'manual',
    ai_confidence: null,
    version: 1,
    created_at: NOW - 33 * 86400_000,
    updated_at: NOW - 8 * 86400_000,
  },
  {
    id: 'user_profile',
    name: '用户资料',
    description: '查看 / 修改用户个人资料（昵称 / 头像 / 邮箱）',
    category: '用户管理',
    project_name: PROJECT_NAME,
    project_root: PROJECT_ROOT,
    related_files: [
      { path: 'src/main/java/com/xxx/controller/UserController.java', role: 'API 入口' },
    ],
    related_apis: [
      { method: 'GET', path: '/api/v1/users/{id}/profile', description: '获取用户资料' },
      { method: 'PUT', path: '/api/v1/users/{id}/profile', description: '更新用户资料' },
    ],
    related_tables: [{ name: 't_user', description: '用户主表' }],
    business_rules: ['头像大小限制 2MB，支持 jpg/png/webp'],
    risk_level: 'low',
    source: 'manual',
    ai_confidence: null,
    version: 1,
    created_at: NOW - 22 * 86400_000,
    updated_at: NOW - 4 * 86400_000,
  },
  {
    id: 'user_oauth_bind',
    name: '第三方账号绑定',
    description: '微信 / 支付宝 / GitHub OAuth 账号绑定解绑',
    category: '用户管理',
    project_name: PROJECT_NAME,
    project_root: PROJECT_ROOT,
    related_files: [
      { path: 'src/main/java/com/xxx/integration/OauthGateway.java', role: '外部依赖' },
    ],
    related_apis: [
      { method: 'POST', path: '/api/v1/users/oauth/bind', description: '绑定第三方账号' },
      { method: 'DELETE', path: '/api/v1/users/oauth/{provider}', description: '解绑第三方账号' },
    ],
    related_tables: [{ name: 't_user_oauth', description: '第三方账号绑定表' }],
    business_rules: ['每个用户最多绑定 1 个微信号'],
    risk_level: 'medium',
    source: 'manual',
    ai_confidence: null,
    version: 1,
    created_at: NOW - 18 * 86400_000,
    updated_at: NOW - 2 * 86400_000,
  },
  // ========== 财务管理 ==========
  {
    id: 'finance_reconcile',
    name: '财务对账',
    description: 't_order 与 t_payment 双向比对，找出 orphan 记录',
    category: '财务管理',
    project_name: PROJECT_NAME,
    project_root: PROJECT_ROOT,
    related_files: [
      { path: 'src/main/java/com/xxx/service/ReconcileService.java', role: '业务逻辑' },
    ],
    related_apis: [
      { method: 'POST', path: '/api/v1/finance/reconcile/run', description: '触发对账' },
      { method: 'GET', path: '/api/v1/finance/reconcile/diff', description: '查看对账差异' },
    ],
    related_tables: [
      { name: 't_order', description: '订单主表' },
      { name: 't_payment', description: '支付流水' },
    ],
    business_rules: ['每日凌晨 3 点自动跑对账', 'orphan 记录超过 100 条触发告警'],
    risk_level: 'high',
    source: 'manual',
    ai_confidence: null,
    version: 1,
    created_at: NOW - 40 * 86400_000,
    updated_at: NOW - 6 * 86400_000,
  },
  {
    id: 'finance_payout',
    name: '商家结算',
    description: '商家应付款计算 + 提现申请 + 打款执行',
    category: '财务管理',
    project_name: PROJECT_NAME,
    project_root: PROJECT_ROOT,
    related_files: [
      { path: 'src/main/java/com/xxx/service/PayoutService.java', role: '业务逻辑' },
    ],
    related_apis: [
      { method: 'POST', path: '/api/v1/finance/payout/apply', description: '申请提现' },
      { method: 'POST', path: '/api/v1/finance/payout/execute', description: '执行打款' },
    ],
    related_tables: [
      { name: 't_merchant_balance', description: '商家余额表' },
      { name: 't_payout_record', description: '打款记录' },
    ],
    business_rules: ['单笔打款 ≥ 5万 需财务总监审批', '每月 5 号出上月账单'],
    risk_level: 'high',
    source: 'manual',
    ai_confidence: null,
    version: 1,
    created_at: NOW - 38 * 86400_000,
    updated_at: NOW - 9 * 86400_000,
  },
  {
    id: 'finance_refund_audit',
    name: '退款审核',
    description: '高金额退款风控审核 + 拦截可疑退款',
    category: '财务管理',
    project_name: PROJECT_NAME,
    project_root: PROJECT_ROOT,
    related_files: [
      { path: 'src/main/java/com/xxx/service/RefundAuditService.java', role: '业务逻辑' },
    ],
    related_apis: [
      { method: 'POST', path: '/api/v1/finance/refund/audit', description: '提交退款审核' },
    ],
    related_tables: [
      { name: 't_refund', description: '退款记录' },
      { name: 't_audit_log', description: '审核日志' },
    ],
    business_rules: ['单笔退款 ≥ 1万 需人工审核', '同一用户 24h 内退款 ≥ 5 次触发风控'],
    risk_level: 'high',
    source: 'manual',
    ai_confidence: null,
    version: 1,
    created_at: NOW - 32 * 86400_000,
    updated_at: NOW - 7 * 86400_000,
  },
  // ========== 库存管理 ==========
  {
    id: 'inventory_stock_in',
    name: '采购入库',
    description: '采购订单创建 + 入库扫码 + 库存自动增加',
    category: '库存管理',
    project_name: PROJECT_NAME,
    project_root: PROJECT_ROOT,
    related_files: [
      { path: 'src/main/java/com/xxx/service/PurchaseService.java', role: '业务逻辑' },
    ],
    related_apis: [
      { method: 'POST', path: '/api/v1/inventory/purchase', description: '创建采购单' },
      { method: 'POST', path: '/api/v1/inventory/stock-in', description: '入库确认' },
    ],
    related_tables: [
      { name: 't_inventory', description: '库存表' },
      { name: 't_purchase_order', description: '采购单' },
    ],
    business_rules: ['入库数量与采购单不一致时拒收', '同一 SKU 库存上限 100000'],
    risk_level: 'medium',
    source: 'manual',
    ai_confidence: null,
    version: 1,
    created_at: NOW - 24 * 86400_000,
    updated_at: NOW - 5 * 86400_000,
  },
  {
    id: 'inventory_stock_out',
    name: '销售出库',
    description: '订单支付成功后自动扣减库存',
    category: '库存管理',
    project_name: PROJECT_NAME,
    project_root: PROJECT_ROOT,
    related_files: [
      { path: 'src/main/java/com/xxx/service/InventoryService.java', role: '业务逻辑' },
    ],
    related_apis: [
      { method: 'POST', path: '/api/v1/inventory/lock', description: '预占库存' },
      { method: 'POST', path: '/api/v1/inventory/deduct', description: '扣减库存' },
    ],
    related_tables: [{ name: 't_inventory', description: '库存表' }],
    business_rules: ['库存不足时拒绝扣减', '扣减失败回滚订单支付'],
    risk_level: 'high',
    source: 'manual',
    ai_confidence: null,
    version: 1,
    created_at: NOW - 26 * 86400_000,
    updated_at: NOW - 4 * 86400_000,
  },
  {
    id: 'inventory_lock',
    name: '库存预占',
    description: '下单时预占库存，超时未支付自动释放',
    category: '库存管理',
    project_name: PROJECT_NAME,
    project_root: PROJECT_ROOT,
    related_files: [
      { path: 'src/main/java/com/xxx/scheduler/InventoryReleaseJob.java', role: '定时任务' },
    ],
    related_apis: [],
    related_tables: [
      { name: 't_inventory', description: '库存表' },
      { name: 't_inventory_lock', description: '预占记录' },
    ],
    business_rules: ['预占 30 分钟未支付自动释放', '预占期间同一 SKU 不允许其他订单预占'],
    risk_level: 'medium',
    source: 'manual',
    ai_confidence: null,
    version: 1,
    created_at: NOW - 21 * 86400_000,
    updated_at: NOW - 3 * 86400_000,
  },
  {
    id: 'inventory_alert',
    name: '库存预警',
    description: '库存低于安全阈值时自动告警 + 通知采购',
    category: '库存管理',
    project_name: PROJECT_NAME,
    project_root: PROJECT_ROOT,
    related_files: [
      { path: 'src/main/java/com/xxx/scheduler/InventoryAlertJob.java', role: '定时任务' },
    ],
    related_apis: [
      { method: 'GET', path: '/api/v1/inventory/alerts', description: '查看库存预警' },
    ],
    related_tables: [{ name: 't_inventory_alert', description: '预警记录' }],
    business_rules: ['阈值可在 Settings 配置', '预警触发后 1 小时内未补货升级告警'],
    risk_level: 'low',
    source: 'manual',
    ai_confidence: null,
    version: 1,
    created_at: NOW - 19 * 86400_000,
    updated_at: NOW - 1 * 86400_000,
  },
  // ========== 报表分析 ==========
  {
    id: 'report_daily_sales',
    name: '日销售报表',
    description: '按日聚合销售数据，生成可下载 Excel 报表',
    category: '报表分析',
    project_name: PROJECT_NAME,
    project_root: PROJECT_ROOT,
    related_files: [
      { path: 'src/main/java/com/xxx/report/SalesReportBuilder.java', role: '报表生成' },
    ],
    related_apis: [
      { method: 'GET', path: '/api/v1/reports/sales/daily', description: '日销售数据' },
      { method: 'GET', path: '/api/v1/reports/sales/daily/export', description: '导出 Excel' },
    ],
    related_tables: [
      { name: 't_order', description: '订单主表' },
      { name: 't_order_item', description: '订单明细' },
    ],
    business_rules: ['数据延迟 1 小时', '保留 90 天历史可查'],
    risk_level: 'low',
    source: 'manual',
    ai_confidence: null,
    version: 1,
    created_at: NOW - 15 * 86400_000,
    updated_at: NOW - 2 * 86400_000,
  },
  {
    id: 'report_user_growth',
    name: '用户增长报表',
    description: '按日 / 周 / 月聚合新用户注册数据 + 留存率',
    category: '报表分析',
    project_name: PROJECT_NAME,
    project_root: PROJECT_ROOT,
    related_files: [
      { path: 'src/main/java/com/xxx/report/UserGrowthReportBuilder.java', role: '报表生成' },
    ],
    related_apis: [
      { method: 'GET', path: '/api/v1/reports/users/growth', description: '用户增长数据' },
    ],
    related_tables: [{ name: 't_user', description: '用户主表' }],
    business_rules: ['留存率分次日 / 7日 / 30日', '渠道来源按注册时 utm 标记'],
    risk_level: 'low',
    source: 'manual',
    ai_confidence: null,
    version: 1,
    created_at: NOW - 13 * 86400_000,
    updated_at: NOW - 1 * 86400_000,
  },
  {
    id: 'report_risk_dashboard',
    name: '风控仪表盘',
    description: '实时显示可疑交易 / 异地登录 / 暴力破解事件',
    category: '报表分析',
    project_name: PROJECT_NAME,
    project_root: PROJECT_ROOT,
    related_files: [
      { path: 'src/main/java/com/xxx/dashboard/RiskDashboardBuilder.java', role: '仪表盘' },
    ],
    related_apis: [
      { method: 'GET', path: '/api/v1/dashboard/risk/realtime', description: '实时风控事件' },
    ],
    related_tables: [
      { name: 't_risk_event', description: '风控事件' },
      { name: 't_login_log', description: '登录日志' },
    ],
    business_rules: ['高危事件自动推送到运营 IM 群', '保留 180 天历史可查'],
    risk_level: 'medium',
    source: 'manual',
    ai_confidence: null,
    version: 1,
    created_at: NOW - 10 * 86400_000,
    updated_at: NOW - 1 * 86400_000,
  },
];
