/**
 * 6 个 mock skills —— Phase 2D V0 演示数据。
 */
import type { Skill } from '@/types/skill';

const NOW = Date.now();

export const MOCK_SKILLS: Skill[] = [
  {
    schema_version: '1.0',
    id: 'db_query_order',
    name: '订单库查询',
    description: '查询 orders_db 库的订单表，支持多维度筛选 + CSV 导出',
    version: '1.0',
    author: '李娜 (DBA)',
    tags: ['database', 'orders', 'query'],
    risk_level: 'low',
    enabled: true,
    role: 'utility',
    trigger_keywords: ['订单', 'order', '查订单', '订单查询', '订单列表'],
    mcp_servers: ['mcp-server-database'],
    allowed_tools: ['db.query', 'db.schema'],
    system_prompt: '你是一名订单数据分析师。优先使用 db.query 工具查询 orders_db.orders 表，支持按 user_id / status / created_at 范围筛选。回答时附加 SQL 解释 + 数据条数 + 采样 3 条样例。涉及大额订单（> 10000）时主动提示风控审核。',
    few_shot_examples: [
      { role: 'user', content: '查一下最近 7 天的未支付订单' },
      { role: 'assistant', content: '我将使用 db.query 查询最近 7 天的 status=\'pending\' 订单。' },
    ],
    source_path: '',
    loaded_at: NOW,
    validation_errors: [],
  },
  {
    schema_version: '1.0',
    id: 'db_query_user',
    name: '用户库查询',
    description: '查询 users_db 库的用户表',
    version: '1.0',
    author: '李娜 (DBA)',
    tags: ['database', 'users', 'query'],
    risk_level: 'low',
    enabled: true,
    role: 'utility',
    trigger_keywords: ['用户', 'user', '查用户', '用户列表', '用户资料'],
    mcp_servers: ['mcp-server-database'],
    allowed_tools: ['db.query', 'db.schema'],
    system_prompt: '你是一名用户数据分析师。使用 db.query 查询 users_db.users 表。',
    few_shot_examples: [],
    source_path: '',
    loaded_at: NOW,
    validation_errors: [],
  },
  {
    schema_version: '1.0',
    id: 'finance_reconcile',
    name: '财务对账',
    description: 't_order 与 t_payment 双向比对，找出 orphan 记录',
    version: '1.0',
    author: '王芳 (财务)',
    tags: ['finance', 'reconcile'],
    risk_level: 'medium',
    enabled: true,
    role: 'utility',
    trigger_keywords: ['对账', 'reconcile', '财务对账', 't_order', 't_payment'],
    mcp_servers: ['mcp-server-database'],
    allowed_tools: ['db.query', 'db.execute'],
    system_prompt: '你是财务对账助手。比对 t_order 与 t_payment 表，生成 orphan 报告。',
    few_shot_examples: [],
    source_path: '',
    loaded_at: NOW,
    validation_errors: [],
  },
  {
    schema_version: '1.0',
    id: 'deploy_rollback',
    name: '紧急回滚',
    description: '生产环境紧急回滚上一版本',
    version: '1.0',
    author: '张伟 (研发)',
    tags: ['deploy', 'rollback', 'emergency'],
    risk_level: 'high',
    enabled: true,
    role: 'reasoning',
    trigger_keywords: ['回滚', 'rollback', '紧急回滚', '部署回滚', '上线回滚'],
    mcp_servers: ['mcp-server-ssh'],
    allowed_tools: ['ssh.exec'],
    system_prompt: '⚠️ 高危操作：执行前必须人工确认。回滚命令：ssh.exec 执行部署脚本 deploy-rollback.sh。',
    few_shot_examples: [],
    source_path: '',
    loaded_at: NOW,
    validation_errors: [],
  },
  {
    schema_version: '1.0',
    id: 'report_daily',
    name: '日报生成',
    description: '每日销售数据汇总报告',
    version: '1.0',
    author: '陈静 (运营)',
    tags: ['report', 'daily'],
    risk_level: 'low',
    enabled: true,
    role: 'execution',
    trigger_keywords: ['日报', 'daily', '销售日报', '生成报告', '报表'],
    mcp_servers: ['mcp-server-database', 'mcp-server-rest'],
    allowed_tools: ['db.query', 'rest.request'],
    system_prompt: '你是日报生成助手。查询昨日订单数据 + 调 rest.request 导出 Excel。',
    few_shot_examples: [],
    source_path: '',
    loaded_at: NOW,
    validation_errors: [],
  },
  {
    schema_version: '1.0',
    id: 'ssh_diagnostic',
    name: 'SSH 诊断',
    description: '远程服务器状态诊断',
    version: '1.0',
    author: '张伟 (研发)',
    tags: ['ssh', 'diagnostic'],
    risk_level: 'medium',
    enabled: true,
    role: 'utility',
    trigger_keywords: ['ssh', '远程', '服务器', '诊断', '远程登录', '服务器状态'],
    mcp_servers: ['mcp-server-ssh'],
    allowed_tools: ['ssh.exec', 'ssh.upload'],
    system_prompt: '你是 SSH 诊断助手。使用 ssh.exec 执行系统状态命令（top / df -h / netstat）。',
    few_shot_examples: [],
    source_path: '',
    loaded_at: NOW,
    validation_errors: [],
  },
];
