"""Phase 15 V0 · .eaide-vite.config.mjs 动态生成器。

按框架注入对应插件：
  - Vue 3  → @vitejs/plugin-vue
  - Vue 2  → vite-plugin-vue2
  - React  → @vitejs/plugin-react（Fast Refresh）
  - Svelte → @sveltejs/vite-plugin-svelte
  - HTML   → 无插件

额外写入：
  - server.host = 127.0.0.1 + 指定端口
  - server.fs.strict 保持 Vite 默认（不放开上级目录）
  - 若设置了 EAIDE_AGENT_PORT，则 server.hmr.clientPort 指向 Agent SSE 端口
    （设计文档 §3.6 —— HMR 状态经 Agent SSE 通道中转）

注意：不 `import { defineConfig } from 'vite'` —— 纯静态项目可能没有
node_modules，Node ESM 无法解析 'vite' 包导致配置加载失败。defineConfig
本质是恒等函数，这里用本地定义替代（V1 e2e 实测发现）。
"""

from __future__ import annotations

import os
from pathlib import Path

from agent.preview.framework_detector import vue_major_version
from agent.preview.models import Framework

CONFIG_FILENAME = ".eaide-vite.config.mjs"


def generate(
    project_path: str | Path,
    framework: Framework,
    port: int,
    *,
    agent_port: int | None = None,
) -> str:
    """生成 Vite 配置文件并写入项目根目录。

    返回配置文件绝对路径（写入失败时抛 OSError）。
    """
    root = Path(project_path)
    root.mkdir(parents=True, exist_ok=True)
    config_path = root / CONFIG_FILENAME

    plugin_lines: list[str] = []
    import_lines: list[str] = []
    if framework == Framework.VUE:
        if vue_major_version(root) == 2:
            import_lines.append("import vue from 'vite-plugin-vue2';")
            plugin_lines.append("  vue(),")
        else:
            import_lines.append("import vue from '@vitejs/plugin-vue';")
            plugin_lines.append("  vue(),")
    elif framework == Framework.REACT:
        import_lines.append("import react from '@vitejs/plugin-react';")
        plugin_lines.append("  react(),")
    elif framework == Framework.SVELTE:
        import_lines.append("import { svelte } from '@sveltejs/vite-plugin-svelte';")
        plugin_lines.append("  svelte(),")

    hmr_block = ""
    agent_port = agent_port or _agent_port_from_env()
    if agent_port is not None:
        hmr_block = (
            f"    hmr: {{\n"
            f"      // HMR 消息经 Agent SSE 通道中转（Phase 15 设计 §3.6）\n"
            f"      clientPort: {agent_port},\n"
            f"      overlay: true,\n"
            f"    }},\n"
        )

    content = (
        "// Auto-generated by EAIDE Phase 15 Live Preview Engine.\n"
        "// 此文件由预览引擎自动生成/覆盖，请勿手改；加入 .gitignore。\n"
        + ("\n".join(import_lines) + "\n" if import_lines else "")
        + "\n"
        "// defineConfig 为恒等函数 —— 本地定义避免无 node_modules 时\n"
        "// 解析 'vite' 包失败（纯静态 HTML 项目）\n"
        "const defineConfig = (c) => c;\n\n"
        "export default defineConfig({\n"
        "  plugins: [\n"
        + ("\n".join(plugin_lines) if plugin_lines else "    // 纯静态 HTML —— 无插件")
        + "\n"
        "  ],\n"
        "  server: {\n"
        f"    host: '127.0.0.1',\n"
        f"    port: {port},\n"
        f"    strictPort: true,\n" + hmr_block + "  },\n"
        "});\n"
    )
    config_path.write_text(content, encoding="utf-8")
    return str(config_path)


def _agent_port_from_env() -> int | None:
    raw = os.environ.get("EAIDE_AGENT_PORT")
    if not raw:
        return None
    try:
        return int(raw)
    except ValueError:
        return None
